sudo: false
addons:
  apt:
    - nunit-console

language: csharp
solution: ./src/MediaUtility/MediaUtility.sln

install:
  - nuget restore ./src/MediaUtility/MediaUtility.sln

script:
  - xbuild ./src/MediaUtility/MediaUtility.sln
  - nunit-console ./src/MediaUtility/TestCases/bin/Debug/TestCases.dll
