sudo: false
addons:
  apt:
    - nunit-console

language: csharp
solution: ./src/MediaUtility/MediaUtility.sln

install:
  - nuget restore ./src/MediaUtility/MediaUtility.sln

script:
  - xbuild ./src/MediaUtility/MediaUtility.sln
<<<<<<< HEAD
  - nunit-console ./src/MediaUtility/TestCases/bin/Debug/TestCases.dll
=======
  - nunit-console ./src/MediaUtility/
>>>>>>> 0249669... added .travis.yml
